version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"  # Jaeger Thrift compact protocol
      - "6832:6832/udp"  # Jaeger Thrift binary protocol
      - "16686:16686"    # Jaeger UI
      - "14268:14268"    # Jaeger Thrift HTTP Collector
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # If you want to collect Zipkin spans via HTTP
      - LOG_LEVEL=info                 # Adjust log level if needed
    restart: unless-stopped

